# Generated by Django 3.1.7 on 2021-03-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20210304_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bgcolor',
        ),
        migrations.AddField(
            model_name='user',
            name='activation',
            field=models.BooleanField(default=False, verbose_name='激活'),
        ),
    ]
